---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-schedule-scaler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-schedule-scaler
  namespace: kube-schedule-scaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-schedule-scaler
subjects:
- kind: ServiceAccount
  name: kube-schedule-scaler
  namespace: kube-schedule-scaler
roleRef:
  kind: ClusterRole
  name: kube-schedule-scaler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-schedule-scaler
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
- apiGroups: ["autoscaling", "extensions"]
  resources:
    - horizontalpodautoscalers
  verbs: ["get", "list", "patch"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-schedule-scaler
  name: kube-schedule-scaler
  namespace: kube-schedule-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-schedule-scaler
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: kube-schedule-scaler
    spec:
      serviceAccountName: kube-schedule-scaler
      containers:
      - name: kube-schedule-scaler
        image: "citizensadvice/kube-schedule-scaler:latest"
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
